# Generated by Django 6.0.5 on 2026-05-19 12:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_postal_de_la_commune', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmpreinteDigitale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doigt', models.CharField(max_length=50)),
                ('empreinte', models.ImageField(upload_to='empreintes/')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaisseCommune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('commune', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caisse', to='mariage.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('operateur', 'Operateur de saisie'), ('officier', 'Officier Etat Civil'), ('bourgmestre', 'Bourgmestre'), ('maire', 'Maire'), ('hierarchie', 'Hierarchie'), ('conjoint', 'Conjoint'), ('citoyen', 'citoyen')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mariage.commune')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(max_length=50, unique=True)),
                ('date_depot', models.DateField()),
                ('objet', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('commune_enregistrement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_enregistres', to='mariage.commune')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('piece_identite', 'Piece identité'), ('acte_naissance', 'Acte naissance'), ('photo', 'Photo'), ('certificat', 'Certificat')], max_length=100)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mariage.dossier')),
            ],
        ),
        migrations.CreateModel(
            name='Epouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('post_nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('piece_identite', models.CharField(max_length=100)),
                ('numero_piece', models.CharField(max_length=100, unique=True)),
                ('photo_carte', models.ImageField(blank=True, null=True, upload_to='cartes_identite/')),
                ('profession', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=20)),
                ('nom_pere', models.CharField(max_length=100)),
                ('nom_mere', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=150)),
                ('nationalite', models.CharField(max_length=100)),
                ('numero_parcelle', models.CharField(max_length=150)),
                ('cellule', models.CharField(max_length=150)),
                ('quartier', models.CharField(max_length=150)),
                ('ville_origine', models.CharField(max_length=150)),
                ('date_delivrance', models.DateField()),
                ('lieu_delivrance', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/epoux/')),
                ('commune_residence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mariage.commune')),
                ('empreinte_digitale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mariage.empreintedigitale')),
            ],
        ),
        migrations.CreateModel(
            name='Epoux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('post_nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('piece_identite', models.CharField(max_length=100)),
                ('numero_piece', models.CharField(max_length=100, unique=True)),
                ('photo_carte', models.ImageField(blank=True, null=True, upload_to='cartes_identite/')),
                ('profession', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=20)),
                ('nom_pere', models.CharField(max_length=100)),
                ('nom_mere', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=150)),
                ('nationalite', models.CharField(max_length=100)),
                ('numero_parcelle', models.CharField(max_length=150)),
                ('cellule', models.CharField(max_length=150)),
                ('quartier', models.CharField(max_length=150)),
                ('ville_origine', models.CharField(max_length=150)),
                ('date_delivrance', models.DateField()),
                ('lieu_delivrance', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/epoux/')),
                ('commune_residence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mariage.commune')),
                ('empreinte_digitale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mariage.empreintedigitale')),
            ],
        ),
        migrations.AddField(
            model_name='dossier',
            name='epouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_epouse', to='mariage.epoux'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='epoux',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_epoux', to='mariage.epoux'),
        ),
        migrations.CreateModel(
            name='Mariage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acte', models.CharField(max_length=50, unique=True)),
                ('date_mariage', models.DateField()),
                ('lieu_mariage', models.CharField(max_length=150)),
                ('regime_matrimonial', models.CharField(max_length=100)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('remarque', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('actif', 'Mariage Actif'), ('divorce', 'Divorcé')], default='actif', max_length=20)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mariage.dossier')),
                ('epouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mariage.epouse')),
                ('epoux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mariage.epoux')),
            ],
        ),
        migrations.CreateModel(
            name='Divorce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_divorce', models.CharField(max_length=50, unique=True)),
                ('date_divorce', models.DateField()),
                ('motif', models.TextField()),
                ('decision_justice', models.FileField(upload_to='divorces/')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('agent_validation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mariage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mariage.mariage')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='mariage.caissecommune')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mariage.dossier')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total_du', models.DecimalField(decimal_places=2, help_text='Le coût total fixé pour le dossier', max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant versé')),
                ('type_paiement', models.CharField(choices=[('avance', 'Avance'), ('totalite', 'Totalité')], default='avance', max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('preuve_paiement', models.FileField(blank=True, null=True, upload_to='paiements/recus/')),
                ('agent_recouvreur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='mariage.dossier')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='Temoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numero_piece', models.CharField(max_length=100, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/temoins/')),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=255)),
                ('piece_identite', models.CharField(max_length=100)),
                ('date_delivrance', models.DateField()),
                ('lieu_delivrance', models.CharField(max_length=150)),
                ('empreinte_digitale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mariage.empreintedigitale')),
            ],
        ),
        migrations.AddField(
            model_name='mariage',
            name='temoins',
            field=models.ManyToManyField(to='mariage.temoin'),
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mariage.province')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mariage.ville'),
        ),
    ]
