# Generated by Django 6.0.5 on 2026-05-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epouse',
            name='cellule',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='epouse',
            name='date_delivrance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='epouse',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='epouse',
            name='lieu_delivrance',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='epouse',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='epouse',
            name='nationalite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='epouse',
            name='nom_mere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='epouse',
            name='nom_pere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='epouse',
            name='numero_parcelle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='epouse',
            name='quartier',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='epouse',
            name='ville_origine',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='epoux',
            name='cellule',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='epoux',
            name='date_delivrance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='epoux',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='epoux',
            name='lieu_delivrance',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='epoux',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='epoux',
            name='nationalite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='epoux',
            name='nom_mere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='epoux',
            name='nom_pere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='epoux',
            name='numero_parcelle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='epoux',
            name='quartier',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='epoux',
            name='ville_origine',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='temoin',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='temoin',
            name='date_delivrance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temoin',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temoin',
            name='lieu_delivrance',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='temoin',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos/temoins/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temoin',
            name='piece_identite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='temoin',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
