# Generated by Django 6.0.5 on 2026-05-19 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariage', '0002_alter_epouse_cellule_alter_epouse_date_delivrance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='epouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_epouse', to='mariage.epouse'),
        ),
    ]
