# Generated by Django 6.0.5 on 2026-05-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariage', '0003_alter_dossier_epouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epouse',
            name='profession',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='epoux',
            name='profession',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
