# Generated by Django 6.0.5 on 2026-05-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariage', '0004_alter_epouse_profession_alter_epoux_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='date_depot',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='objet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
