# Generated by Django 6.0.5 on 2026-05-19 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariage', '0005_alter_dossier_date_depot_alter_dossier_objet'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoin',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temoins', to='mariage.dossier'),
        ),
        migrations.AddField(
            model_name='temoin',
            name='provenance',
            field=models.CharField(blank=True, choices=[('EPOUX', 'Époux'), ('EPOUSE', 'Épouse')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='temoin',
            name='numero_piece',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='temoin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/temoins/'),
        ),
        migrations.AlterField(
            model_name='temoin',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
