# Generated by Django 6.0.5 on 2026-05-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariage', '0006_temoin_dossier_temoin_provenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoin',
            name='postnom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
