# Generated by Django 6.0.5 on 2026-06-07 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariage', '0008_reconnaissancefaciale_alter_caissecommune_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commune',
            options={'verbose_name': 'Commune', 'verbose_name_plural': 'Communes'},
        ),
        migrations.AddField(
            model_name='commune',
            name='est_mairie',
            field=models.BooleanField(default=False, help_text="Commune virtuelle « Mairie » pour les mariages célébrés à l'hôtel de ville."),
        ),
        migrations.AddField(
            model_name='dossier',
            name='celebre_a_mairie',
            field=models.BooleanField(default=False, help_text="Mariage célébré à la mairie (hôtel de ville) plutôt qu'en commune."),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='affecte_mairie',
            field=models.BooleanField(default=False, help_text="Agent affecté à la mairie (mariages célébrés à l'hôtel de ville)."),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='epouse_lie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_conjoint', to='mariage.epouse'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='epoux_lie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_conjoint', to='mariage.epoux'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='ville',
            field=models.ForeignKey(blank=True, help_text="Ville d'affectation pour le maire (accès à toutes les communes + mairie).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maires', to='mariage.ville'),
        ),
        migrations.AlterField(
            model_name='caissecommune',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='divorce',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empreintedigitale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='epouse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='epouse',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/epouse/'),
        ),
        migrations.AlterField(
            model_name='epoux',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='province',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reconnaissancefaciale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='temoin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='mariage.commune'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ville',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ProfilCitoyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('post_nom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('numero_piece', models.CharField(blank=True, max_length=50)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=150)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('nationalite', models.CharField(default='Congolaise', max_length=100)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='citoyens/photos/')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_citoyen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionCaptureMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('type_capture', models.CharField(choices=[('empreinte', 'Empreinte digitale'), ('photo', 'Photo / reconnaissance faciale')], max_length=20)),
                ('role_verif', models.CharField(blank=True, max_length=10)),
                ('contexte', models.CharField(choices=[('dossier_verif', 'Vérification dossier'), ('mariage', 'Mariage'), ('divorce', 'Divorce')], default='dossier_verif', max_length=30)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='capture_mobile/')),
                ('image_base64', models.TextField(blank=True)),
                ('consomme', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_capture', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
