# Generated by Django 5.2.14 on 2026-06-13 17:43

import django.db.models.deletion
from django.db import migrations, models


def migrer_hierarchie_vers_president(apps, schema_editor):
    Utilisateur = apps.get_model('mariage', 'Utilisateur')
    Utilisateur.objects.filter(role='hierarchie').update(role='president')


class Migration(migrations.Migration):

    dependencies = [
        ('mariage', '0011_utilisateur_identite_officielle'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='province_affectation',
            field=models.ForeignKey(
                blank=True,
                help_text="Province d'affectation pour le Gouverneur et son Agent.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='autorites_provinciales',
                to='mariage.province',
            ),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(
                choices=[
                    ('operateur', 'Operateur de saisie'),
                    ('officier', 'Officier Etat Civil'),
                    ('bourgmestre', 'Bourgmestre'),
                    ('maire', 'Maire de la ville'),
                    ('gouverneur', 'Gouverneur'),
                    ('agent_gouverneur', 'Agent Gouverneur'),
                    ('ministre_national', 'Ministre National'),
                    ('agent_ministre_national', 'Agent Ministre National'),
                    ('premier_ministre', 'Premier Ministre'),
                    ('agent_premier_ministre', 'Agent Premier Ministre'),
                    ('president', 'Président'),
                    ('agent_president', 'Agent Président'),
                    ('conjoint', 'Conjoint'),
                    ('citoyen', 'citoyen'),
                ],
                max_length=30,
            ),
        ),
        migrations.RunPython(migrer_hierarchie_vers_president, migrations.RunPython.noop),
    ]
