# Generated by Django 5.2.14 on 2026-06-13 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mariage', '0012_roles_autorites_province_quittances'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cadastre', models.CharField(max_length=100, unique=True)),
                ('proprietaire', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=255)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='mariage.commune')),
            ],
            options={
                'verbose_name': 'Parcelle',
                'verbose_name_plural': 'Parcelles',
                'ordering': ['numero_cadastre'],
            },
        ),
        migrations.CreateModel(
            name='QuittanceParcellaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('periode', models.CharField(help_text='Ex. 2024, 2024-T1, année fiscale…', max_length=50)),
                ('date', models.DateField()),
                ('commune', models.ForeignKey(help_text='Commune de rattachement pour le filtrage géographique.', on_delete=django.db.models.deletion.CASCADE, related_name='quittances_parcellaires', to='mariage.commune')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quittances', to='gestion_quittance_parcellaire.parcelle')),
            ],
            options={
                'verbose_name': 'Quittance parcellaire',
                'verbose_name_plural': 'Quittances parcellaires',
                'ordering': ['-date', '-pk'],
            },
        ),
    ]
